### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by larsbrinkhoff** [rdrop-exit/No-Frills-Forth#1]
Hello,

I'm curious what this repository is about?

**Comment by rdrop-exit** [comment]
Hi Lars,

It's a placeholder for an eventual redesign/reimplementation of an old umbilical Forth cross-compiler to a 64-bit Unix host.

Cheers,
 Mark

**Comment by larsbrinkhoff** [comment]
Thanks; looking forward to see it!
